name: Init CI/CD

on:
  push:
    branches:
      - release/KREM-229
  pull_request:
    branches:
      - release/KREM-229
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # === Backend (NestJS) ===
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: Dashboard.Backend/package-lock.json

      - name: Install Backend dependencies
        working-directory: Dashboard.Backend
        run: npm ci

      - name: Lint Backend
        working-directory: Dashboard.Backend
        run: npm run lint --if-present

      - name: Build Backend
        working-directory: Dashboard.Backend
        run: npm run build

      - name: Test Backend
        working-directory: Dashboard.Backend
        run: npm run test --if-present
        continue-on-error: true

      # === Frontend (React / Next.js) ===
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: Dashboard.Frontend/package-lock.json

      - name: Install Frontend dependencies
        working-directory: Dashboard.Frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: Dashboard.Frontend
        run: npm run lint --if-present

      - name: Build Frontend
        working-directory: Dashboard.Frontend
        run: CI=false npm run build   # lint uyarılarını hata saymaz

      - name: Test Frontend
        working-directory: Dashboard.Frontend
        run: npm run test --if-present
        continue-on-error: true       # test hatası olsa bile pipeline devam eder

      # === Artifact oluşturma ===
      - name: Archive build artifacts
        if: github.ref == 'refs/heads/release/KREM-229'
        run: |
          mkdir -p artifacts/backend artifacts/frontend
          cp -r Dashboard.Backend/dist artifacts/backend/
          cp -r Dashboard.Frontend/dist artifacts/frontend/
          cp Dashboard.Backend/package*.json artifacts/backend/
          cp Dashboard.Frontend/package*.json artifacts/frontend/
